### ISSUE TITLE
Secret Shadowy Supertaggers

### ISSUE THREAD

**Issue by BenGWeeks** [teambtcmap/btcmap-data#204] opened 2022-10-04 09:09 UTC
On the following page:

[https://github.com/teambtcmap/btcmap-data/wiki/Tagging-Instructions](https://github.com/teambtcmap/btcmap-data/wiki/Tagging-Instructions)

It references the "[Shadowy Supertaggers](https://github.com/orgs/teambtcmap/teams/shadowy-supertaggers)" team, however, clicking the link takes me to a 404 page. Perhaps this is a "secret" (non-visible team)?

**Comment by dadofsambonzuki** [comment] 2022-10-04 09:38
Hey Ben - I don't get a 404. I get a GH login page if I'm not logged-in, or go straight to the page if I am logged in.

Team is set to visible.

**Comment by BenGWeeks** [comment] 2022-10-04 09:52
Here's what I see:

![image](https://user-images.githubusercontent.com/5950171/193790022-f8cb30ec-6cb9-4f24-b5af-2ced25a575ca.png)

**Comment by secondl1ght** [comment] 2022-10-19 13:24
Closing this because we cannot reproduce - opening in a private browser tab takes you to the GH login page as @dadofsambonzuki suggests.

**Closed by secondl1ght** 2022-10-19 13:24 UTC
Labels: bug
